version: "3.8"

services:
  huay-backend:
    image: huay_backend:1.0.0
    container_name: huay-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # ฝั่งซ้าย: เครื่อง Host (ตามใจคุณ) | ฝั่งขวา: ใน Container (ต้องตรงกับที่เจอจริง)
      - ./uploads:/app/uploads
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
