name: CI/CD for Huay Backend System

# Trigger the workflow on push to prod branch
on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Deploy the application on the remote server
      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            # Navigate to the application directory
            cd /home/api/huay-backend
            # Pull latest code from repository
            git fetch origin prod
            git reset --hard origin/prod
            # Stop existing containers
            docker-compose down
            # Build and start containers (build on server)
            docker-compose up -d --build
            # Wait for containers to start
            sleep 5
            # Show logs
            docker-compose logs
            # Clean up unused Docker resources
            docker system prune -f
          EOF
