name: CI/CD for Huay Backend System

# Trigger the workflow on push to prod branch
on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the source code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image with specified tag
      - name: Build Docker image
        run: |
          docker build -t huay_backend:1.0.0 .

      # Export the Docker image to a tar file for transfer
      - name: Save Docker image to tar
        run: |
          docker save -o huay_backend.tar huay_backend:1.0.0

      # Transfer the Docker image tar file to the deployment server
      - name: Copy tar to server using SCP
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no huay_backend.tar $SERVER_USERNAME@$SERVER_HOST:/tmp/huay_backend.tar

      # Deploy the application on the remote server
      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            # Load the Docker image from tar file
            docker load -i /tmp/huay_backend.tar
            # Clean up the transferred tar file
            rm /tmp/huay_backend.tar
            # Navigate to the application directory
            cd /home/api/huay-backend
            # Stop existing containers and remove orphaned containers
            docker-compose down --remove-orphans
            # Start the application in detached mode
            docker-compose up --no-build -d
          EOF

      # Clean up build artifacts locally
      - name: Clean up local tar
        run: |
          # Remove the local Docker image tar file to free up space and avoid clutter
          rm -f huay_backend.tar
